#!/usr/bin/env php
<?php
/**
 * Start Script
 * Usage:
 *   ./yii tcp/run
 */

defined('YII_DEBUG') or define('YII_DEBUG', true); // true or false
defined('YII_ENV') or define('YII_ENV', 'dev'); // dev or test or prod

require(__DIR__ . '/../../vendor/autoload.php');
require(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
